/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/router/src/router_module';
import * as import8 from '@angular/http/src/http_module';
import * as import9 from '@angular/material/core/ripple/ripple';
import * as import10 from '@angular/material/button/button';
import * as import11 from '@angular/material/card/card';
import * as import12 from '@angular/material/checkbox/checkbox';
import * as import13 from '@angular/material/core/line/line';
import * as import14 from '@angular/material/grid-list/grid-list';
import * as import15 from '@angular/material/input/input';
import * as import16 from '@angular/material/list/list';
import * as import17 from '@angular/material/progress-bar/progress-bar';
import * as import18 from '@angular/material/progress-circle/progress-circle';
import * as import19 from '@angular/material/select/index';
import * as import20 from '@angular/material/sidenav/sidenav';
import * as import21 from '@angular/material/core/portal/portal-directives';
import * as import22 from '@angular/material/tabs/tabs';
import * as import23 from '@angular/material/toolbar/toolbar';
import * as import24 from '@angular/material/core/rtl/dir';
import * as import25 from '@angular/material/core/a11y/index';
import * as import26 from '@angular/material/button-toggle/button-toggle';
import * as import27 from '@angular/material/core/overlay/overlay-directives';
import * as import28 from '@angular/material/dialog/dialog';
import * as import29 from '@angular/material/icon/icon';
import * as import30 from '@angular/material/menu/menu';
import * as import31 from '@angular/material/radio/radio';
import * as import32 from '@angular/material/slider/slider';
import * as import33 from '@angular/material/slide-toggle/slide-toggle';
import * as import34 from '@angular/material/snack-bar/snack-bar';
import * as import35 from '@angular/material/tooltip/tooltip';
import * as import36 from '@angular/material/module';
import * as import37 from 'angular2-moment/moment.module';
import * as import38 from 'ng2-charts/components/charts/charts';
import * as import39 from 'angular2-infinite-scroll/src/index';
import * as import40 from '@angular/common/src/localization';
import * as import41 from '@angular/core/src/application_init';
import * as import42 from '@angular/core/src/testability/testability';
import * as import43 from '@angular/core/src/application_ref';
import * as import44 from '@angular/core/src/linker/compiler';
import * as import45 from '@angular/material/core/gestures/MdGestureConfig';
import * as import46 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import47 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import48 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import49 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import50 from '@angular/core/src/linker/view_utils';
import * as import51 from '@angular/platform-browser/src/browser/title';
import * as import52 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import53 from '@angular/http/src/backends/browser_xhr';
import * as import54 from '@angular/http/src/base_response_options';
import * as import55 from '@angular/http/src/backends/xhr_backend';
import * as import56 from '@angular/http/src/base_request_options';
import * as import57 from '@angular/material/core/a11y/live-announcer';
import * as import58 from '@angular/material/core/a11y/interactivity-checker';
import * as import59 from '@angular/material/core/coordination/unique-selection-dispatcher';
import * as import60 from '@angular/material/core/overlay/overlay-container';
import * as import61 from '@angular/material/core/overlay/position/viewport-ruler';
import * as import62 from '@angular/material/core/overlay/position/overlay-position-builder';
import * as import63 from '@angular/material/core/overlay/overlay';
import * as import64 from '@angular/material/icon/icon-registry';
import * as import65 from 'angular2-infinite-scroll/src/axis-resolver';
import * as import66 from 'angular2-infinite-scroll/src/position-resolver';
import * as import67 from '@angular/common/src/location/location';
import * as import68 from '@angular/router/src/url_tree';
import * as import69 from '@angular/router/src/router_outlet_map';
import * as import70 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import71 from './api.service';
import * as import72 from './snackbar/snackbar.service';
import * as import73 from '@angular/core/src/di/injector';
import * as import74 from '../../node_modules/@angular/material/dialog/dialog-container.ngfactory';
import * as import75 from '../../node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory';
import * as import76 from '../../node_modules/@angular/material/snack-bar/simple-snack-bar.ngfactory';
import * as import77 from '../../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import78 from './users/users.component.ngfactory';
import * as import79 from './user/user.component.ngfactory';
import * as import80 from './transactions/transactions.component.ngfactory';
import * as import81 from './metrics/metrics.component.ngfactory';
import * as import82 from './config/config.component.ngfactory';
import * as import83 from './page-not-found/page-not-found.component.ngfactory';
import * as import84 from './user/user-remove-dialog/user-remove-dialog.component.ngfactory';
import * as import85 from './user/user-edit-dialog/user-edit-dialog.component.ngfactory';
import * as import86 from './app/app.component.ngfactory';
import * as import87 from '@angular/core/src/application_tokens';
import * as import88 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import89 from '@angular/platform-browser/src/dom/events/key_events';
import * as import90 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import91 from '@angular/core/src/zone/ng_zone';
import * as import92 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import93 from '@angular/common/src/location/platform_location';
import * as import94 from '@angular/common/src/location/location_strategy';
import * as import95 from './users/users.component';
import * as import96 from './user/user.component';
import * as import97 from './transactions/transactions.component';
import * as import98 from './metrics/metrics.component';
import * as import99 from './config/config.component';
import * as import100 from './page-not-found/page-not-found.component';
import * as import101 from '@angular/router/src/router';
import * as import102 from '@angular/core/src/console';
import * as import103 from '@angular/core/src/i18n/tokens';
import * as import104 from '@angular/core/src/error_handler';
import * as import105 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import106 from '@angular/platform-browser/src/dom/animation_driver';
import * as import107 from '@angular/core/src/render/api';
import * as import108 from '@angular/core/src/security';
import * as import109 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import110 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import111 from '@angular/http/src/interfaces';
import * as import112 from '@angular/http/src/http';
import * as import113 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import114 from '@angular/router/src/router_config_loader';
import * as import115 from '@angular/router/src/router_state';
import * as import116 from '@angular/core/src/i18n/tokens';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ROUTER_FORROOT_GUARD_5:any;
  _RouterModule_6:import7.RouterModule;
  _HttpModule_7:import8.HttpModule;
  _MdRippleModule_8:import9.MdRippleModule;
  _MdButtonModule_9:import10.MdButtonModule;
  _MdCardModule_10:import11.MdCardModule;
  _MdCheckboxModule_11:import12.MdCheckboxModule;
  _MdLineModule_12:import13.MdLineModule;
  _MdGridListModule_13:import14.MdGridListModule;
  _MdInputModule_14:import15.MdInputModule;
  _MdListModule_15:import16.MdListModule;
  _MdProgressBarModule_16:import17.MdProgressBarModule;
  _MdProgressCircleModule_17:import18.MdProgressCircleModule;
  _MdSelectModule_18:import19.MdSelectModule;
  _MdSidenavModule_19:import20.MdSidenavModule;
  _PortalModule_20:import21.PortalModule;
  _MdTabsModule_21:import22.MdTabsModule;
  _MdToolbarModule_22:import23.MdToolbarModule;
  _RtlModule_23:import24.RtlModule;
  _A11yModule_24:import25.A11yModule;
  _MdButtonToggleModule_25:import26.MdButtonToggleModule;
  _OverlayModule_26:import27.OverlayModule;
  _MdDialogModule_27:import28.MdDialogModule;
  _MdIconModule_28:import29.MdIconModule;
  _MdMenuModule_29:import30.MdMenuModule;
  _MdRadioModule_30:import31.MdRadioModule;
  _MdSliderModule_31:import32.MdSliderModule;
  _MdSlideToggleModule_32:import33.MdSlideToggleModule;
  _MdSnackBarModule_33:import34.MdSnackBarModule;
  _MdTooltipModule_34:import35.MdTooltipModule;
  _MaterialRootModule_35:import36.MaterialRootModule;
  _MomentModule_36:import37.MomentModule;
  _ChartsModule_37:import38.ChartsModule;
  _InfiniteScrollModule_38:import39.InfiniteScrollModule;
  _AppModule_39:import1.AppModule;
  __LOCALE_ID_40:any;
  __NgLocalization_41:import40.NgLocaleLocalization;
  _ErrorHandler_42:any;
  _ApplicationInitStatus_43:import41.ApplicationInitStatus;
  _Testability_44:import42.Testability;
  _ApplicationRef__45:import43.ApplicationRef_;
  __ApplicationRef_46:any;
  __Compiler_47:import44.Compiler;
  __APP_ID_48:any;
  __DOCUMENT_49:any;
  __HAMMER_GESTURE_CONFIG_50:import45.MdGestureConfig;
  __EVENT_MANAGER_PLUGINS_51:any[];
  __EventManager_52:import46.EventManager;
  __DomSharedStylesHost_53:import47.DomSharedStylesHost;
  __AnimationDriver_54:any;
  __DomRootRenderer_55:import48.DomRootRenderer_;
  __RootRenderer_56:any;
  __DomSanitizer_57:import49.DomSanitizerImpl;
  __Sanitizer_58:any;
  __ViewUtils_59:import50.ViewUtils;
  __IterableDiffers_60:any;
  __KeyValueDiffers_61:any;
  __SharedStylesHost_62:any;
  __Title_63:import51.Title;
  __RadioControlRegistry_64:import52.RadioControlRegistry;
  __BrowserXhr_65:import53.BrowserXhr;
  __ResponseOptions_66:import54.BaseResponseOptions;
  __XSRFStrategy_67:any;
  __XHRBackend_68:import55.XHRBackend;
  __RequestOptions_69:import56.BaseRequestOptions;
  __Http_70:any;
  __MdLiveAnnouncer_71:import57.MdLiveAnnouncer;
  __InteractivityChecker_72:import58.InteractivityChecker;
  __MdUniqueSelectionDispatcher_73:import59.MdUniqueSelectionDispatcher;
  __OverlayContainer_74:import60.OverlayContainer;
  __ViewportRuler_75:import61.ViewportRuler;
  __OverlayPositionBuilder_76:import62.OverlayPositionBuilder;
  __Overlay_77:import63.Overlay;
  __MdDialog_78:import28.MdDialog;
  __MdIconRegistry_79:import64.MdIconRegistry;
  __MdSnackBar_80:import34.MdSnackBar;
  __AxisResolverFactory_81:import65.AxisResolverFactory;
  __PositionResolverFactory_82:import66.PositionResolverFactory;
  __ROUTER_CONFIGURATION_83:any;
  __LocationStrategy_84:any;
  __Location_85:import67.Location;
  __UrlSerializer_86:import68.DefaultUrlSerializer;
  __RouterOutletMap_87:import69.RouterOutletMap;
  __NgModuleFactoryLoader_88:import70.SystemJsNgModuleLoader;
  __ROUTES_89:any[];
  __Router_90:any;
  __ActivatedRoute_91:any;
  __APP_BOOTSTRAP_LISTENER_92:any[];
  __ApiService_93:import71.ApiService;
  __SnackbarService_94:import72.SnackbarService;
  __TRANSLATIONS_FORMAT_95:any;
  constructor(parent:import73.Injector) {
    super(parent,[
      import74.MdDialogContainerNgFactory,
      import75.MdSnackBarContainerNgFactory,
      import76.SimpleSnackBarNgFactory,
      import77.TooltipComponentNgFactory,
      import78.UsersComponentNgFactory,
      import79.UserComponentNgFactory,
      import80.TransactionsComponentNgFactory,
      import81.MetricsComponentNgFactory,
      import82.ConfigComponentNgFactory,
      import83.PageNotFoundComponentNgFactory,
      import84.UserRemoveDialogComponentNgFactory,
      import85.UserEditDialogComponentNgFactory,
      import86.AppComponentNgFactory
    ]
    ,[import86.AppComponentNgFactory]);
  }
  get _LOCALE_ID_40():any {
    if ((this.__LOCALE_ID_40 == (null as any))) { (this.__LOCALE_ID_40 = (null as any)); }
    return this.__LOCALE_ID_40;
  }
  get _NgLocalization_41():import40.NgLocaleLocalization {
    if ((this.__NgLocalization_41 == (null as any))) { (this.__NgLocalization_41 = new import40.NgLocaleLocalization(this._LOCALE_ID_40)); }
    return this.__NgLocalization_41;
  }
  get _ApplicationRef_46():any {
    if ((this.__ApplicationRef_46 == (null as any))) { (this.__ApplicationRef_46 = this._ApplicationRef__45); }
    return this.__ApplicationRef_46;
  }
  get _Compiler_47():import44.Compiler {
    if ((this.__Compiler_47 == (null as any))) { (this.__Compiler_47 = new import44.Compiler()); }
    return this.__Compiler_47;
  }
  get _APP_ID_48():any {
    if ((this.__APP_ID_48 == (null as any))) { (this.__APP_ID_48 = import87._appIdRandomProviderFactory()); }
    return this.__APP_ID_48;
  }
  get _DOCUMENT_49():any {
    if ((this.__DOCUMENT_49 == (null as any))) { (this.__DOCUMENT_49 = import4._document()); }
    return this.__DOCUMENT_49;
  }
  get _HAMMER_GESTURE_CONFIG_50():import45.MdGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_50 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_50 = new import45.MdGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_50;
  }
  get _EVENT_MANAGER_PLUGINS_51():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_51 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_51 = [
      new import88.DomEventsPlugin(),
      new import89.KeyEventsPlugin(),
      new import90.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_50)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_51;
  }
  get _EventManager_52():import46.EventManager {
    if ((this.__EventManager_52 == (null as any))) { (this.__EventManager_52 = new import46.EventManager(this._EVENT_MANAGER_PLUGINS_51,this.parent.get(import91.NgZone))); }
    return this.__EventManager_52;
  }
  get _DomSharedStylesHost_53():import47.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_53 == (null as any))) { (this.__DomSharedStylesHost_53 = new import47.DomSharedStylesHost(this._DOCUMENT_49)); }
    return this.__DomSharedStylesHost_53;
  }
  get _AnimationDriver_54():any {
    if ((this.__AnimationDriver_54 == (null as any))) { (this.__AnimationDriver_54 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_54;
  }
  get _DomRootRenderer_55():import48.DomRootRenderer_ {
    if ((this.__DomRootRenderer_55 == (null as any))) { (this.__DomRootRenderer_55 = new import48.DomRootRenderer_(this._DOCUMENT_49,this._EventManager_52,this._DomSharedStylesHost_53,this._AnimationDriver_54)); }
    return this.__DomRootRenderer_55;
  }
  get _RootRenderer_56():any {
    if ((this.__RootRenderer_56 == (null as any))) { (this.__RootRenderer_56 = import92._createConditionalRootRenderer(this._DomRootRenderer_55,this.parent.get(import92.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_56;
  }
  get _DomSanitizer_57():import49.DomSanitizerImpl {
    if ((this.__DomSanitizer_57 == (null as any))) { (this.__DomSanitizer_57 = new import49.DomSanitizerImpl()); }
    return this.__DomSanitizer_57;
  }
  get _Sanitizer_58():any {
    if ((this.__Sanitizer_58 == (null as any))) { (this.__Sanitizer_58 = this._DomSanitizer_57); }
    return this.__Sanitizer_58;
  }
  get _ViewUtils_59():import50.ViewUtils {
    if ((this.__ViewUtils_59 == (null as any))) { (this.__ViewUtils_59 = new import50.ViewUtils(this._RootRenderer_56,this._APP_ID_48,this._Sanitizer_58)); }
    return this.__ViewUtils_59;
  }
  get _IterableDiffers_60():any {
    if ((this.__IterableDiffers_60 == (null as any))) { (this.__IterableDiffers_60 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_60;
  }
  get _KeyValueDiffers_61():any {
    if ((this.__KeyValueDiffers_61 == (null as any))) { (this.__KeyValueDiffers_61 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_61;
  }
  get _SharedStylesHost_62():any {
    if ((this.__SharedStylesHost_62 == (null as any))) { (this.__SharedStylesHost_62 = this._DomSharedStylesHost_53); }
    return this.__SharedStylesHost_62;
  }
  get _Title_63():import51.Title {
    if ((this.__Title_63 == (null as any))) { (this.__Title_63 = new import51.Title()); }
    return this.__Title_63;
  }
  get _RadioControlRegistry_64():import52.RadioControlRegistry {
    if ((this.__RadioControlRegistry_64 == (null as any))) { (this.__RadioControlRegistry_64 = new import52.RadioControlRegistry()); }
    return this.__RadioControlRegistry_64;
  }
  get _BrowserXhr_65():import53.BrowserXhr {
    if ((this.__BrowserXhr_65 == (null as any))) { (this.__BrowserXhr_65 = new import53.BrowserXhr()); }
    return this.__BrowserXhr_65;
  }
  get _ResponseOptions_66():import54.BaseResponseOptions {
    if ((this.__ResponseOptions_66 == (null as any))) { (this.__ResponseOptions_66 = new import54.BaseResponseOptions()); }
    return this.__ResponseOptions_66;
  }
  get _XSRFStrategy_67():any {
    if ((this.__XSRFStrategy_67 == (null as any))) { (this.__XSRFStrategy_67 = import8._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_67;
  }
  get _XHRBackend_68():import55.XHRBackend {
    if ((this.__XHRBackend_68 == (null as any))) { (this.__XHRBackend_68 = new import55.XHRBackend(this._BrowserXhr_65,this._ResponseOptions_66,this._XSRFStrategy_67)); }
    return this.__XHRBackend_68;
  }
  get _RequestOptions_69():import56.BaseRequestOptions {
    if ((this.__RequestOptions_69 == (null as any))) { (this.__RequestOptions_69 = new import56.BaseRequestOptions()); }
    return this.__RequestOptions_69;
  }
  get _Http_70():any {
    if ((this.__Http_70 == (null as any))) { (this.__Http_70 = import8.httpFactory(this._XHRBackend_68,this._RequestOptions_69)); }
    return this.__Http_70;
  }
  get _MdLiveAnnouncer_71():import57.MdLiveAnnouncer {
    if ((this.__MdLiveAnnouncer_71 == (null as any))) { (this.__MdLiveAnnouncer_71 = new import57.MdLiveAnnouncer(this.parent.get(import57.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__MdLiveAnnouncer_71;
  }
  get _InteractivityChecker_72():import58.InteractivityChecker {
    if ((this.__InteractivityChecker_72 == (null as any))) { (this.__InteractivityChecker_72 = new import58.InteractivityChecker()); }
    return this.__InteractivityChecker_72;
  }
  get _MdUniqueSelectionDispatcher_73():import59.MdUniqueSelectionDispatcher {
    if ((this.__MdUniqueSelectionDispatcher_73 == (null as any))) { (this.__MdUniqueSelectionDispatcher_73 = new import59.MdUniqueSelectionDispatcher()); }
    return this.__MdUniqueSelectionDispatcher_73;
  }
  get _OverlayContainer_74():import60.OverlayContainer {
    if ((this.__OverlayContainer_74 == (null as any))) { (this.__OverlayContainer_74 = new import60.OverlayContainer()); }
    return this.__OverlayContainer_74;
  }
  get _ViewportRuler_75():import61.ViewportRuler {
    if ((this.__ViewportRuler_75 == (null as any))) { (this.__ViewportRuler_75 = new import61.ViewportRuler()); }
    return this.__ViewportRuler_75;
  }
  get _OverlayPositionBuilder_76():import62.OverlayPositionBuilder {
    if ((this.__OverlayPositionBuilder_76 == (null as any))) { (this.__OverlayPositionBuilder_76 = new import62.OverlayPositionBuilder(this._ViewportRuler_75)); }
    return this.__OverlayPositionBuilder_76;
  }
  get _Overlay_77():import63.Overlay {
    if ((this.__Overlay_77 == (null as any))) { (this.__Overlay_77 = new import63.Overlay(this._OverlayContainer_74,this,this._OverlayPositionBuilder_76)); }
    return this.__Overlay_77;
  }
  get _MdDialog_78():import28.MdDialog {
    if ((this.__MdDialog_78 == (null as any))) { (this.__MdDialog_78 = new import28.MdDialog(this._Overlay_77,this)); }
    return this.__MdDialog_78;
  }
  get _MdIconRegistry_79():import64.MdIconRegistry {
    if ((this.__MdIconRegistry_79 == (null as any))) { (this.__MdIconRegistry_79 = new import64.MdIconRegistry(this._Http_70)); }
    return this.__MdIconRegistry_79;
  }
  get _MdSnackBar_80():import34.MdSnackBar {
    if ((this.__MdSnackBar_80 == (null as any))) { (this.__MdSnackBar_80 = new import34.MdSnackBar(this._Overlay_77,this._MdLiveAnnouncer_71)); }
    return this.__MdSnackBar_80;
  }
  get _AxisResolverFactory_81():import65.AxisResolverFactory {
    if ((this.__AxisResolverFactory_81 == (null as any))) { (this.__AxisResolverFactory_81 = new import65.AxisResolverFactory()); }
    return this.__AxisResolverFactory_81;
  }
  get _PositionResolverFactory_82():import66.PositionResolverFactory {
    if ((this.__PositionResolverFactory_82 == (null as any))) { (this.__PositionResolverFactory_82 = new import66.PositionResolverFactory(this._AxisResolverFactory_81)); }
    return this.__PositionResolverFactory_82;
  }
  get _ROUTER_CONFIGURATION_83():any {
    if ((this.__ROUTER_CONFIGURATION_83 == (null as any))) { (this.__ROUTER_CONFIGURATION_83 = {}); }
    return this.__ROUTER_CONFIGURATION_83;
  }
  get _LocationStrategy_84():any {
    if ((this.__LocationStrategy_84 == (null as any))) { (this.__LocationStrategy_84 = import7.provideLocationStrategy(this.parent.get(import93.PlatformLocation),this.parent.get(import94.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_83)); }
    return this.__LocationStrategy_84;
  }
  get _Location_85():import67.Location {
    if ((this.__Location_85 == (null as any))) { (this.__Location_85 = new import67.Location(this._LocationStrategy_84)); }
    return this.__Location_85;
  }
  get _UrlSerializer_86():import68.DefaultUrlSerializer {
    if ((this.__UrlSerializer_86 == (null as any))) { (this.__UrlSerializer_86 = new import68.DefaultUrlSerializer()); }
    return this.__UrlSerializer_86;
  }
  get _RouterOutletMap_87():import69.RouterOutletMap {
    if ((this.__RouterOutletMap_87 == (null as any))) { (this.__RouterOutletMap_87 = new import69.RouterOutletMap()); }
    return this.__RouterOutletMap_87;
  }
  get _NgModuleFactoryLoader_88():import70.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_88 == (null as any))) { (this.__NgModuleFactoryLoader_88 = new import70.SystemJsNgModuleLoader(this._Compiler_47,this.parent.get(import70.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_88;
  }
  get _ROUTES_89():any[] {
      if ((this.__ROUTES_89 == (null as any))) { (this.__ROUTES_89 = [[
        {
          path: '',
          component: import95.UsersComponent
        }
        ,
        {
          path: 'users/:userId',
          component: import96.UserComponent
        }
        ,
        {
          path: 'users/:userId/transactions',
          component: import97.TransactionsComponent
        }
        ,
        {
          path: 'metrics',
          component: import98.MetricsComponent
        }
        ,
        {
          path: 'config',
          component: import99.ConfigComponent
        }
        ,
        {
          path: '**',
          component: import100.PageNotFoundComponent
        }

      ]
    ]); }
    return this.__ROUTES_89;
  }
  get _Router_90():any {
    if ((this.__Router_90 == (null as any))) { (this.__Router_90 = import7.setupRouter(this._ApplicationRef_46,this._UrlSerializer_86,this._RouterOutletMap_87,this._Location_85,this,this._NgModuleFactoryLoader_88,this._Compiler_47,this._ROUTES_89,this._ROUTER_CONFIGURATION_83)); }
    return this.__Router_90;
  }
  get _ActivatedRoute_91():any {
    if ((this.__ActivatedRoute_91 == (null as any))) { (this.__ActivatedRoute_91 = import7.rootRoute(this._Router_90)); }
    return this.__ActivatedRoute_91;
  }
  get _APP_BOOTSTRAP_LISTENER_92():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_92 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_92 = [import7.initialRouterNavigation(this._Router_90,this._ROUTER_CONFIGURATION_83)]); }
    return this.__APP_BOOTSTRAP_LISTENER_92;
  }
  get _ApiService_93():import71.ApiService {
    if ((this.__ApiService_93 == (null as any))) { (this.__ApiService_93 = new import71.ApiService(this._Http_70)); }
    return this.__ApiService_93;
  }
  get _SnackbarService_94():import72.SnackbarService {
    if ((this.__SnackbarService_94 == (null as any))) { (this.__SnackbarService_94 = new import72.SnackbarService()); }
    return this.__SnackbarService_94;
  }
  get _TRANSLATIONS_FORMAT_95():any {
    if ((this.__TRANSLATIONS_FORMAT_95 == (null as any))) { (this.__TRANSLATIONS_FORMAT_95 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_95;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ROUTER_FORROOT_GUARD_5 = import7.provideForRootGuard(this.parent.get(import101.Router,(null as any)));
    this._RouterModule_6 = new import7.RouterModule(this._ROUTER_FORROOT_GUARD_5);
    this._HttpModule_7 = new import8.HttpModule();
    this._MdRippleModule_8 = new import9.MdRippleModule();
    this._MdButtonModule_9 = new import10.MdButtonModule();
    this._MdCardModule_10 = new import11.MdCardModule();
    this._MdCheckboxModule_11 = new import12.MdCheckboxModule();
    this._MdLineModule_12 = new import13.MdLineModule();
    this._MdGridListModule_13 = new import14.MdGridListModule();
    this._MdInputModule_14 = new import15.MdInputModule();
    this._MdListModule_15 = new import16.MdListModule();
    this._MdProgressBarModule_16 = new import17.MdProgressBarModule();
    this._MdProgressCircleModule_17 = new import18.MdProgressCircleModule();
    this._MdSelectModule_18 = new import19.MdSelectModule();
    this._MdSidenavModule_19 = new import20.MdSidenavModule();
    this._PortalModule_20 = new import21.PortalModule();
    this._MdTabsModule_21 = new import22.MdTabsModule();
    this._MdToolbarModule_22 = new import23.MdToolbarModule();
    this._RtlModule_23 = new import24.RtlModule();
    this._A11yModule_24 = new import25.A11yModule();
    this._MdButtonToggleModule_25 = new import26.MdButtonToggleModule();
    this._OverlayModule_26 = new import27.OverlayModule();
    this._MdDialogModule_27 = new import28.MdDialogModule();
    this._MdIconModule_28 = new import29.MdIconModule();
    this._MdMenuModule_29 = new import30.MdMenuModule();
    this._MdRadioModule_30 = new import31.MdRadioModule();
    this._MdSliderModule_31 = new import32.MdSliderModule();
    this._MdSlideToggleModule_32 = new import33.MdSlideToggleModule();
    this._MdSnackBarModule_33 = new import34.MdSnackBarModule();
    this._MdTooltipModule_34 = new import35.MdTooltipModule();
    this._MaterialRootModule_35 = new import36.MaterialRootModule();
    this._MomentModule_36 = new import37.MomentModule();
    this._ChartsModule_37 = new import38.ChartsModule();
    this._InfiniteScrollModule_38 = new import39.InfiniteScrollModule();
    this._AppModule_39 = new import1.AppModule();
    this._ErrorHandler_42 = import4.errorHandler();
    this._ApplicationInitStatus_43 = new import41.ApplicationInitStatus(this.parent.get(import41.APP_INITIALIZER,(null as any)));
    this._Testability_44 = new import42.Testability(this.parent.get(import91.NgZone));
    this._ApplicationRef__45 = new import43.ApplicationRef_(this.parent.get(import91.NgZone),this.parent.get(import102.Console),this,this._ErrorHandler_42,this,this._ApplicationInitStatus_43,this.parent.get(import42.TestabilityRegistry,(null as any)),this._Testability_44);
    return this._AppModule_39;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_5; }
    if ((token === import7.RouterModule)) { return this._RouterModule_6; }
    if ((token === import8.HttpModule)) { return this._HttpModule_7; }
    if ((token === import9.MdRippleModule)) { return this._MdRippleModule_8; }
    if ((token === import10.MdButtonModule)) { return this._MdButtonModule_9; }
    if ((token === import11.MdCardModule)) { return this._MdCardModule_10; }
    if ((token === import12.MdCheckboxModule)) { return this._MdCheckboxModule_11; }
    if ((token === import13.MdLineModule)) { return this._MdLineModule_12; }
    if ((token === import14.MdGridListModule)) { return this._MdGridListModule_13; }
    if ((token === import15.MdInputModule)) { return this._MdInputModule_14; }
    if ((token === import16.MdListModule)) { return this._MdListModule_15; }
    if ((token === import17.MdProgressBarModule)) { return this._MdProgressBarModule_16; }
    if ((token === import18.MdProgressCircleModule)) { return this._MdProgressCircleModule_17; }
    if ((token === import19.MdSelectModule)) { return this._MdSelectModule_18; }
    if ((token === import20.MdSidenavModule)) { return this._MdSidenavModule_19; }
    if ((token === import21.PortalModule)) { return this._PortalModule_20; }
    if ((token === import22.MdTabsModule)) { return this._MdTabsModule_21; }
    if ((token === import23.MdToolbarModule)) { return this._MdToolbarModule_22; }
    if ((token === import24.RtlModule)) { return this._RtlModule_23; }
    if ((token === import25.A11yModule)) { return this._A11yModule_24; }
    if ((token === import26.MdButtonToggleModule)) { return this._MdButtonToggleModule_25; }
    if ((token === import27.OverlayModule)) { return this._OverlayModule_26; }
    if ((token === import28.MdDialogModule)) { return this._MdDialogModule_27; }
    if ((token === import29.MdIconModule)) { return this._MdIconModule_28; }
    if ((token === import30.MdMenuModule)) { return this._MdMenuModule_29; }
    if ((token === import31.MdRadioModule)) { return this._MdRadioModule_30; }
    if ((token === import32.MdSliderModule)) { return this._MdSliderModule_31; }
    if ((token === import33.MdSlideToggleModule)) { return this._MdSlideToggleModule_32; }
    if ((token === import34.MdSnackBarModule)) { return this._MdSnackBarModule_33; }
    if ((token === import35.MdTooltipModule)) { return this._MdTooltipModule_34; }
    if ((token === import36.MaterialRootModule)) { return this._MaterialRootModule_35; }
    if ((token === import37.MomentModule)) { return this._MomentModule_36; }
    if ((token === import38.ChartsModule)) { return this._ChartsModule_37; }
    if ((token === import39.InfiniteScrollModule)) { return this._InfiniteScrollModule_38; }
    if ((token === import1.AppModule)) { return this._AppModule_39; }
    if ((token === import103.LOCALE_ID)) { return this._LOCALE_ID_40; }
    if ((token === import40.NgLocalization)) { return this._NgLocalization_41; }
    if ((token === import104.ErrorHandler)) { return this._ErrorHandler_42; }
    if ((token === import41.ApplicationInitStatus)) { return this._ApplicationInitStatus_43; }
    if ((token === import42.Testability)) { return this._Testability_44; }
    if ((token === import43.ApplicationRef_)) { return this._ApplicationRef__45; }
    if ((token === import43.ApplicationRef)) { return this._ApplicationRef_46; }
    if ((token === import44.Compiler)) { return this._Compiler_47; }
    if ((token === import87.APP_ID)) { return this._APP_ID_48; }
    if ((token === import105.DOCUMENT)) { return this._DOCUMENT_49; }
    if ((token === import90.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_50; }
    if ((token === import46.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_51; }
    if ((token === import46.EventManager)) { return this._EventManager_52; }
    if ((token === import47.DomSharedStylesHost)) { return this._DomSharedStylesHost_53; }
    if ((token === import106.AnimationDriver)) { return this._AnimationDriver_54; }
    if ((token === import48.DomRootRenderer)) { return this._DomRootRenderer_55; }
    if ((token === import107.RootRenderer)) { return this._RootRenderer_56; }
    if ((token === import49.DomSanitizer)) { return this._DomSanitizer_57; }
    if ((token === import108.Sanitizer)) { return this._Sanitizer_58; }
    if ((token === import50.ViewUtils)) { return this._ViewUtils_59; }
    if ((token === import109.IterableDiffers)) { return this._IterableDiffers_60; }
    if ((token === import110.KeyValueDiffers)) { return this._KeyValueDiffers_61; }
    if ((token === import47.SharedStylesHost)) { return this._SharedStylesHost_62; }
    if ((token === import51.Title)) { return this._Title_63; }
    if ((token === import52.RadioControlRegistry)) { return this._RadioControlRegistry_64; }
    if ((token === import53.BrowserXhr)) { return this._BrowserXhr_65; }
    if ((token === import54.ResponseOptions)) { return this._ResponseOptions_66; }
    if ((token === import111.XSRFStrategy)) { return this._XSRFStrategy_67; }
    if ((token === import55.XHRBackend)) { return this._XHRBackend_68; }
    if ((token === import56.RequestOptions)) { return this._RequestOptions_69; }
    if ((token === import112.Http)) { return this._Http_70; }
    if ((token === import57.MdLiveAnnouncer)) { return this._MdLiveAnnouncer_71; }
    if ((token === import58.InteractivityChecker)) { return this._InteractivityChecker_72; }
    if ((token === import59.MdUniqueSelectionDispatcher)) { return this._MdUniqueSelectionDispatcher_73; }
    if ((token === import60.OverlayContainer)) { return this._OverlayContainer_74; }
    if ((token === import61.ViewportRuler)) { return this._ViewportRuler_75; }
    if ((token === import62.OverlayPositionBuilder)) { return this._OverlayPositionBuilder_76; }
    if ((token === import63.Overlay)) { return this._Overlay_77; }
    if ((token === import28.MdDialog)) { return this._MdDialog_78; }
    if ((token === import64.MdIconRegistry)) { return this._MdIconRegistry_79; }
    if ((token === import34.MdSnackBar)) { return this._MdSnackBar_80; }
    if ((token === import65.AxisResolverFactory)) { return this._AxisResolverFactory_81; }
    if ((token === import66.PositionResolverFactory)) { return this._PositionResolverFactory_82; }
    if ((token === import7.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_83; }
    if ((token === import94.LocationStrategy)) { return this._LocationStrategy_84; }
    if ((token === import67.Location)) { return this._Location_85; }
    if ((token === import68.UrlSerializer)) { return this._UrlSerializer_86; }
    if ((token === import69.RouterOutletMap)) { return this._RouterOutletMap_87; }
    if ((token === import113.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_88; }
    if ((token === import114.ROUTES)) { return this._ROUTES_89; }
    if ((token === import101.Router)) { return this._Router_90; }
    if ((token === import115.ActivatedRoute)) { return this._ActivatedRoute_91; }
    if ((token === import87.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_92; }
    if ((token === import71.ApiService)) { return this._ApiService_93; }
    if ((token === import72.SnackbarService)) { return this._SnackbarService_94; }
    if ((token === import116.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_95; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__45.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);